### PR TITLE
Serialization improvement for objects with multiple primitive values

### PR DESCRIPTION
**Pull request by Scooletz**
Primitive value serializers can now provide the size of the buffer they use during serialization/deserialization by overriding `PreallocatedByteBufferSize`. This gives a hint to a code generator and enables to call `GetBuffer` only once during serialization/deserialization and memoize  an obtained array in a variable. This removes calls to the session object reusing one var instead.

All the signatures of static methods ``ReadValueImpl` & `WriteValueImpl` accepts now `byte[]` instead of the session parameter.

### CODE REVIEW

**Comment by Scooletz** [comment]
What do you think @rogeralsing ? For multiple primitives this could be an improvement. I know this couples a bit `ValueSerializer` with the `DefaultCodeGenerator` but for now, I have no better idea how to implement this.

**Comment by rogeralsing** [comment]
@Scooletz, so what it does is that it checks what field of an object that has the biggest buffer and then assigns a buffer of this size to a var, and then reuse that var to avoid calls to GetBuffer, right?
And the assignment is done per serialization graph, so it is concurrency safe?

**Comment by Scooletz** [comment]
That's correct. It uses GetBuffer from session only once per
deserialization graph, at the very beginning, if it finds any serializer
that requires a byte array (this check is done once, during emit).

7 sie 2016 09:28 "Roger Johansson" notifications@github.com napisał(a):

**Comment by rogeralsing** [comment]
There is no significant speed improvement here, but we are saving clock cycles now so I guess that is expected.
This PR managed to push the perf test down to 530 ms for 1 mil roundtrips, where the best run before was around 540ish

**Comment by rogeralsing** [comment]
perf

There is not a lot we can play with here. writing to the stream, and converting strings to utf8 are the biggest bottlenecks right now.

**Comment by Scooletz** [comment]
Thank you for merging. We're saving calls to `GetBuffer`, that's for sure.

:+1: for not having much left beyond the `Stream` access.  That's why `protobuf-net` has a built-in buffer which reads from stream once and then it operates on the retrieved chunk. It saves `Stream` virtual calls and gives you a simpler abstract to work with: effectively `ArraySegment<byte>`. This can almost remove the need for a session and a helper buffer when reading.
Another part is a kind of `Stream` you write to. If it's a memory stream, maybe we could get a direct access to the buffer. If that was a long buffer `byte*`, we could optimize for this as well. I think I'll need to reread the code and it's usage in `Akka` to come with a nice targeted proposal.

**Comment by rogeralsing** [comment]
I've played around with the ArraySegment<byte> that are used in MS Bond and the BufferPool in Protobuf.net.
When used in Wire, the overhead of just touching `interlocked` hurts our performance.
Same goes for copying the byte segment buffer onto the stream. 

It might be useful for extremely large object graphs with lots of strings etc. but where we are right now, I have not been able to benefit from those techniques yet.

I've also tried the same BufferPool trick for pooling sessions, but that also hurts perf.

**Comment by Scooletz** [comment]
Thank you for sharing this. I won't spend  time on this then. Maybe some
`unsafe` spike only, but I'm not promising anything ;-)

7 sie 2016 17:43 "Roger Johansson" notifications@github.com napisał(a):

**Pull request merged**
