### PR TITLE
Netcore3 Fix

### PR DESCRIPTION
**Pull request by Jaben**
Fixes issue with .NET Core 3.x. Issue #146

### CODE REVIEW

**Comment by Jaben** [comment]
@rogeralsing PRESS THE BUTTON! :)

**Comment by mookid8000** [comment]
@rogeralsing Hi Roger, any chance you could release a 0.8.3 with this fix in it soon? 🙂

**Comment by Jaben** [comment]
Thank you @rogeralsing !! Any change of a new nuget?

**Comment by Gulfam-CDON** [comment]
https://www.nuget.org/packages/Hyperion/0.9.13

**Comment by gulfamabbas** [comment]
https://github.com/akkadotnet/Hyperion

**Comment by mookid8000** [comment]
In case anyone followed the [Rebus.Wire](https://github.com/rebus-org/Rebus.Wire) trail here – Rebus now has a Hyperion serializer 👉 https://github.com/rebus-org/Rebus.Hyperion

Since Hyperion seems to be a maintained version of Wire, one should probably use that instead.

@rogeralsing great work btw. 👍

**Comment by vbatr** [comment]
Hi @rogeralsing,

Could you please update nuget package with fix to .net core 3.0?

**Comment by stbraley** [comment]
I just hit this. Anyway to get a 0.8.3 release?

**Comment by kocoglu** [comment]
Hi @rogeralsing 
I can not find new nuget package with fix.  Can you publish new nuget package?

**Pull request merged**
